<a href="https://colab.research.google.com/github/BrassicaNapus/Pytorch-Study/blob/main/PyTorch_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# View (Reshape)

In [2]:
import numpy as np
import torch

In [3]:
t = np.array([
              [[0, 1, 2],
               [3, 4, 5]],
              
              [[6, 7, 8],
               [9, 10, 11]]
])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [4]:
print(ft.view([-1, 3])) # (2, 2, 3) -> (2 x 2, 3)
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [5]:
print(ft.view([-1, 1, 3])) # (2, 2, 3) -> (2 x 2, 3) -> (2 x 2, 1, 3)
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


# Squeeze

In [7]:
ft = torch.FloatTensor([[0],
                        [1],
                        [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [8]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


# Unsqueeze

In [9]:
ft = torch.FloatTensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [10]:
print(ft.unsqueeze(0)) # |ft| = (3,) -> (1, 3)
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [11]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [12]:
print(ft.unsqueeze(1)) # |ft| = (3,) -> (3, 1)
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [13]:
print(ft.unsqueeze(-1)) # dim = -1 -> dim = 1
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


# Type Casting

In [14]:
lt = torch.LongTensor([1, 2, 3, 4])
lt

tensor([1, 2, 3, 4])

In [16]:
lt.float()

tensor([1., 2., 3., 4.])

In [17]:
bt = torch.ByteTensor([True, False, False, True])
bt

tensor([1, 0, 0, 1], dtype=torch.uint8)

In [18]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


# concatenate

In [19]:
x = torch.FloatTensor([[1, 2], # |x| = |y| = (2, 2)
                       [3, 4]])
y = torch.FloatTensor([[5, 6],
                       [7, 8]])

In [20]:
print(torch.cat([x, y], dim=0)) # (2, 2) -> (4, 2)
print(torch.cat([x, y], dim=1)) # (2, 2) -> (2, 4)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


# Stacking

In [22]:
x = torch.FloatTensor([1, 4]) # |x| = |y| = |z| = (2,)
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [26]:
print(torch.stack([x, y, z])) # (2,) -> (3, 2)
print(torch.stack([x, y, z], dim=1)) # (2,) -> (2, 3)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [27]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


# Ones and Zeros

In [29]:
x = torch.FloatTensor([[0, 1, 2],
                       [2, 1, 0]])
x

tensor([[0., 1., 2.],
        [2., 1., 0.]])

In [30]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# In-place Operation

In [31]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

In [32]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
