<a href="https://colab.research.google.com/github/BrassicaNapus/Pytorch-Study/blob/main/PyTorch_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1D Array with Numpy

In [1]:
import numpy as np
import torch

In [3]:
t = np.array([0, 1, 2, 3, 4, 5, 6])
t

array([0, 1, 2, 3, 4, 5, 6])

In [4]:
print('Rank of t: ', t.ndim) #차원
print('Shape of t: ', t.shape) #하나의 차원에 7개의 elements가 들어있다

Rank of t:  1
Shape of t:  (7,)


In [7]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) #Element
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) #Slicing
print('t[:2] t[3:] = ', t[:2], t[3:]) #Slicing

t[0] t[1] t[-1] =  0 1 6
t[2:5] t[4:-1] =  [2 3 4] [4 5]
t[:2] t[3:] =  [0 1] [3 4 5 6]


# 2D Array with Numpy

In [9]:
t = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])
t

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
print('Rank of t: ', t.ndim) #차원
print('Shape of t: ', t.shape) #2개의 차원에 (4, 3)개의 elements가 들어있다

Rank of t:  2
Shape of t:  (4, 3)


# 1D Array with pytorch

In [13]:
t = torch.FloatTensor([0, 1, 2, 3, 4, 5, 6])
t

tensor([0., 1., 2., 3., 4., 5., 6.])

In [14]:
print(t.dim()) #rank
print(t.shape) #shape
print(t.size()) #shape
print(t[0], t[1], t[-1]) #Element
print(t[2:5], t[4:-1]) #Slicing
print(t[:2], t[3:]) #Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


# 2D Array with pytorch

In [15]:
t = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9],
                       [10, 11, 12]])
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [24]:
print(t.dim()) #rank
print(t.shape) #shape
print(t.size()) #shape
print(t[0], t[1], t[-1]) #Element
print(t[:, 2])
print(t[:, 2].size())
print(t[:, :-1])
print(t[:, :-1].size())

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([1., 2., 3.]) tensor([4., 5., 6.]) tensor([10., 11., 12.])
tensor([ 3.,  6.,  9., 12.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])
torch.Size([4, 2])


# Broadcasting

In [25]:
# same shape
m1 = torch.FloatTensor([[3, 3]]) # |m1| = (1, 2)
m2 = torch.FloatTensor([[2, 2]]) # |m1| = |m2|
m1 + m2

tensor([[5., 5.]])

In [26]:
# vector + scalar
m1 = torch.FloatTensor([[1, 2]]) # |m1| = (1, 2)
m2 = torch.FloatTensor([3]) # |m2| = (1,) -> (1, 2)
m1 + m2

tensor([[4., 5.]])

In [28]:
# 2 x 1 vector + 1 x 2 vector
m1 = torch.FloatTensor([[1, 2]]) # (1, 2) -> (2, 2)
m2 = torch.FloatTensor([[3],
                        [4]]) # (2, 1) -> (2, 2)
m1 + m2

tensor([[4., 5.],
        [5., 6.]])

# Multiplication vs Matrix Multiplication

In [33]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2],
                        [3, 4]])
m2 = torch.FloatTensor([[1],
                        [2]])
print('shape of matrix 1: ', m1.shape) # 2 x 2
print('shape of matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1, 2],
                        [3, 4]])
m2 = torch.FloatTensor([[1],
                        [2]])
print('shape of matrix 1: ', m1.shape) # 2 x 2
print('shape of matrix 2: ', m2.shape) # 2 x 1 -> 2 x 2
print(m1 * m2) # 2 x 2
print(m1.mul(m2))


-------------
Mul vs Matmul
-------------
shape of matrix 1:  torch.Size([2, 2])
shape of matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
shape of matrix 1:  torch.Size([2, 2])
shape of matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


# Mean

In [34]:
t = torch.FloatTensor([1, 2])
t.mean()

tensor(1.5000)

In [35]:
# cant use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

mean(): input dtype should be either floating point or complex dtypes. Got Long instead.


In [36]:
t = torch.FloatTensor([[1, 2],
                       [3, 4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [38]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


# Sum

In [39]:
t = torch.FloatTensor([[1, 2],
                       [3, 4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [41]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


# Max and Argmax

In [42]:
t = torch.FloatTensor([[1, 2],
                       [3, 4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [43]:
t.max()

tensor(4.)

In [46]:
print(t.max(dim=0)) #return two values: max and argmax(index)
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1]) # index값

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [47]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
